#!/usr/bin/sh

echo "accepts log w/ failures on stdin"

TESTS=`awk '/^FAILED tests/ {print $2}'`

PYTHONPATH=\
$PWD/contrib/pyln-client:\
$PWD/contrib/pyln-testing:\
$PWD/contrib/pyln-proto \
TEST_DEBUG=1 \
DEVELOPER=1 \
VALGRIND=0 \
SUBDAEMON='hsmd:remote_hsmd' \
REMOTE_SIGNER_CMD=$(pwd)/../validating-lightning-signer/target/debug/server \
REMOTE_SIGNER_ALLOWLIST=$(pwd)/contrib/remote_hsmd/TESTING_ALLOWLIST \
pytest \
$TESTS \
-n=32 --timeout=300 --timeout_method=thread -v
