#!/usr/bin/sh

THETEST=$1

PYTHONPATH=\
$PWD/contrib/pyln-client:\
$PWD/contrib/pyln-testing:\
$PWD/contrib/pyln-proto \
TEST_DEBUG=1 \
DEVELOPER=1 \
VALGRIND=0 \
SLOW_MACHINE=1 \
SUBDAEMON='hsmd:remote_hsmd' \
REMOTE_SIGNER_CMD=$(pwd)/../rust-lightning-signer/target/debug/server \
pytest \
$THETEST \
-v --timeout=300 --timeout_method=thread -x
