#!/usr/bin/sh

SUBDAEMON='hsmd:remote_hsmd' \
REMOTE_SIGNER_CMD=$(pwd)/../rust-lightning-signer/target/debug/server \
make \
-j16 PYTEST_PAR=32 \
DEVELOPER=1 \
VALGRIND=0 \
SLOW_MACHINE=0 \
PYTEST_MOREOPTS='--timeout=300 --timeout_method=thread' \
pytest

